# nq jobscript | qsub -P long -l h_vmem=4G -N My_job_name_here
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/1.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/2.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/3.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/4.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/5.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/6.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/7.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/8.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/9.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/10.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/11.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/12.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/13.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/14.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/15.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/16.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/17.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/18.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/19.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/20.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/21.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/22.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/23.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/24.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/25.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/26.txt
bash $HOME/proj_db_infer_pipe/temp/compt_crypto_dbd_pid.sh pids_dbd_list/27.txt
