# nq run_infer_fire_motif.sh | qsub -P long -l h_vmem=8G -N My_job_name_here
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/1.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/2.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/3.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/4.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/5.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/6.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/7.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/8.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/9.txt
bash $HOME/proj_db_infer_pipe/scripts/infer_fire_motif.sh $HOME/proj_db_infer_pipe/resources/fly_promoter_seq/rsat_Drosophila_yakuba_upstream_-2000_+200.filtered.fasta $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/motif_inference/Dyak $HOME/proj_db_infer_pipe/output/fly_network_cellCycle_orthologs/network_np/Dyak.rids_list/10.txt
