# nq jobscript | qsub -P long -tc 10 -N My_job_name_here
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_1.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_2.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_3.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_4.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_5.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_6.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_7.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_8.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_9.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_10.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_11.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_12.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_13.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_14.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_15.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_16.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_17.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_18.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_19.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_20.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_21.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_22.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_23.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_24.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_25.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_26.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_27.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid 
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_28.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_29.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_30.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_31.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid
bash $HOME/proj_db_infer_pipe/scripts/compt_fimo_scan.sh resources/cisbp_1.02/cisbp_dmel_dir_evid_motif_list/cisbp_motifs_32.txt resources/cisbp_1.02/cisbp_all_pfms/ output/fly_cisbp_-2000_+200_fimo_dir_evid

