# nq jobscript | qsub -P long -l h_vmem=4G -N My_job_name_here
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/1.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/2.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/3.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/4.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/5.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/6.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/7.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/8.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/9.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/10.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/11.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/12.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/13.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/14.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/15.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/16.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/17.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/18.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/19.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/20.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/21.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/22.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/23.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/24.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/25.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/26.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/27.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/28.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/29.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/30.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/31.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/32.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/33.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/34.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/35.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/36.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/37.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/38.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/39.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/40.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/41.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/42.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/43.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/44.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/45.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/46.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/47.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/48.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/49.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/50.txt
bash $HOME/proj_db_infer_pipe/scripts/compt_dbd_pid_wrap.sh pids_dbd_list/51.txt
